# Generated by Django 2.2.2 on 2019-10-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191025_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='fieldname',
            new_name='image',
        ),
    ]
